# SPDX-FileCopyrightText: 2026 Iva Horn
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = [
    "**/*.json",
    "**/*.md",
    ".gitignore",
    ".swift-version",
    ".swiftformat",
]
SPDX-FileCopyrightText = "2026 Iva Horn"
SPDX-License-Identifier = "MIT"
