// SPDX-FileCopyrightText: 2026 Iva Horn
// SPDX-License-Identifier: MIT

///
/// A subset of the response body returned by `GET /containers/{id}/json`.
///
/// ``NextcloudContainerManager/delete(_:)`` inspects a container before removing it to read the deployment label written during ``NextcloudContainerManager/deploy(configuration:)``, which tells it whether a Redis sidecar and a user-defined network must be torn down alongside the Nextcloud container. ``NextcloudContainerManager/deploy(configuration:)`` inspects the container it just created to learn the name it ended up with, which is the only place a name generated by the Docker Engine can be read from.
///
struct ContainerInspectResponse: Decodable {
    ///
    /// The container's configuration as reported by the Docker Engine.
    ///
    struct Config: Decodable {
        ///
        /// The user-defined labels attached to the container at creation time, or `nil` when none were set.
        ///
        let Labels: [String: String]?
    }

    ///
    /// The configuration the container was created with.
    ///
    let Config: Config

    ///
    /// The container's name, reported with a leading slash, for example `/nextcloud-tests`.
    ///
    /// Set from the `name` query parameter of `POST /containers/create` when one was given, and generated by the Docker Engine otherwise.
    ///
    let Name: String
}
