// SPDX-FileCopyrightText: 2026 Iva Horn
// SPDX-License-Identifier: MIT

import Foundation

///
/// Reads the name a container carries from the Docker Engine.
///
/// A name generated by the Docker Engine is not reported anywhere else — `POST /containers/create` answers with the identifier alone — so ``NextcloudContainerManager/deploy(configuration:)`` looks it up here to fill ``NextcloudContainer/name`` regardless of whether the caller pinned it through ``NextcloudConfiguration/name``. The Docker Engine reports the name with a leading slash, which is stripped so the value can be passed back into the API as an identifier.
///
/// - Parameters:
///     - id: The container identifier to inspect.
///     - client: The Docker Engine client to use.
///
/// - Returns: The container name without its leading slash.
///
/// - Throws: Another case of ``nextcloudcontainermanagererror`` for a docker engine request that fails, times out or cannot be made.
///
func containerName(of id: String, using client: DockerEngineClient) async throws -> String {
    let response = try await client.get(path: "/containers/\(id)/json")

    try response.checked([200])

    let inspect = try JSONDecoder().decode(ContainerInspectResponse.self, from: response.body)

    return String(inspect.Name.drop(while: { $0 == "/" }))
}
